version: "3.9"

services:
    web:
        build: .
        ports:
            - "5000:8000"
        depends_on:
            - redis
        volumes:
            - .:/app
        environment:
            - DEBUG=1
            - DJANGO_SETTINGS_MODULE=forum_project.settings
        command: python forum_project/manage.py runserver 0.0.0.0:8000

    redis:
        image: redis:7
        ports:
            - "6379:6379"
